apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins/label: "java-overwrite"
spec:
  containers:
  - image: "cloudbees/cloudbees-core-agent"
    imagePullPolicy: "IfNotPresent"
    name: "jnlp"
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/home/jenkins/agent"
  - args:
    - "cat"
    command:
    - "/bin/sh"
    - "-c"
    image: "maven:3.6.3-jdk-8"
    imagePullPolicy: "IfNotPresent"
    name: "maven"
  hostNetwork: false
  nodeSelector:
    kubernetes.io/os: "linux"
  restartPolicy: "Never"
  volumes:
  - emptyDir:
      medium: ""
    name: "workspace-volume"  