apiVersion: v1
kind: Pod
metadata:
  name: generic-dca-stretch
spec:
  containers:
    - name: "maven"
      image: "maven:3.6.3-jdk-8"
      command:
      - bash
    - name: jnlp
      image: cloudbees/cloudbees-core-agent:2.235.2.3
      volumeMounts:
        - name: override-java-security
          subPath: java.config
          mountPath: /etc/crypto-policies/back-ends/java.config
  volumes:
    - name: override-java-security
      configMap:
        name: override-java-security