apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins/label: "java-overwrite"
spec:
  containers:
  - args:
    - "cat"
    command:
    - "/bin/sh"
    - "-c"
    image: "maven:3.6.3-jdk-8"
    name: "maven"